<?php


/**
 * Implements hook_menu().
 */
function zigpad_export_menu() {
  $items['zigpad/config'] = array(
    'title' => 'Zigpad Export',
    'page callback' => 'zigpad_export_config',
    'access callback' => TRUE,
  );
  return $items;
}


function zigpad_export_config() {

  $xml = new SimpleXMLElement('<?xml version="1.0" ?><config created="2001-12-31T12:00:00" xmlns:tns="http://www.example.org/AMoCoConfig/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/AMoCoConfig/config.xsd"></config>');

  // Add presentations to XML.
  $pnids = db_query("SELECT nid FROM {node} WHERE type = 'presentation'")->fetchCol();
  $presentations = $xml->addChild('presentations');
  foreach (node_load_multiple($pnids) as $node) {
    $presentation = $presentations->addChild('presentation');
    $presentation->addAttribute('name', $node->title);
    if ($comment = field_get_items('node', $node, 'field_comment')) {
      $presentation->addChild('comment', $comment[0]['value']);
    }
    if ($scenes = field_get_items('node', $node, 'field_scenes')) {
      $sequence = $presentation->addChild('sceneSequence');
      foreach ($scenes as $scene) {
        $sequence->addChild('sceneRef', $scene['nid']);
      }
    }
  } 


  // Add scenes to XML.
  $snids = db_query("SELECT nid FROM {node} WHERE type = 'scene'")->fetchCol();
  $scenes = $xml->addChild('scenes');
  foreach (node_load_multiple($snids) as $node) {
    $scene = $scenes->addChild('scene');
    $scene->addAttribute('id', $node->nid);
    $scene->addAttribute('name', $node->title);
    if ($picture = field_get_items('node', $node, 'field_picture')) {
      $scene->addChild('picture')->addAttribute('src', file_create_url($picture[0]['uri']));
    }
    if ($actions = field_get_items('node', $node, 'field_actions')) {
      $sequence = $scene->addChild('actionSequence');
      foreach ($actions as $action) {
        $sequence->addChild('actionRef', $action['nid']);
      }
    }
  } 

  // Add actions to XML.
  $anids = db_query("SELECT nid FROM {node} WHERE type = 'action'")->fetchCol();
  $actions = $xml->addChild('actions');
  foreach (node_load_multiple($anids) as $node) {
    $action = $actions->addChild('action');
    $action->addAttribute('id', $node->nid);
    $action->addAttribute('name', $node->title);
    if ($picture = field_get_items('node', $node, 'field_picture')) {
      $action->addChild('icon')->addAttribute('src', file_create_url($picture[0]['uri']));
    }
    if ($command = field_get_items('node', $node, 'field_command')) {
      $action->addChild('command', $command[0]['value']);
    }
    $action->addChild('standardAction', 'false');
  }

  header('Content-Type: application/xml');
  echo $xml->asXML();
}
